name: MacOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest
    env:
        CTEST_PARALLEL_LEVEL: 2
        cc: /usr/bin/gcc $CFLAGS -fno-semantic-interposition
        c++: /usr/bin/g++ $CXXFLAGS -fno-semantic-interposition
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
      - run: brew install llvm jemalloc git pipx
      - run: git submodule update --init --recursive
      - name: Set up Python and install cmake-format
        run: |
            pipx install cmakelang
      - run: sed -i '' 's/print\-file\-name\=\${\_clang\_modules\_json\_impl}\.modules\.json/print\-file\-name\=\/opt\/homebrew\/opt\/llvm\/lib\/c\+\+\/libc\+\+.modules\.json/' /opt/homebrew/share/cmake/Modules/Compiler/Clang-CXX-CXXImportStd.cmake
      - run: grep print-file-name /opt/homebrew/share/cmake/Modules/Compiler/Clang-CXX-CXXImportStd.cmake
      - name: Add LLVM to PATH
        run: |
            echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH
            echo "CPPFLAGS=-I$(brew --prefix llvm)/include" >> $GITHUB_ENV
            echo "LDFLAGS=-L$LLVM_PREFIX/lib/c++ -Wl,-rpath,$LLVM_PREFIX/lib/c++ -lc++" >> $GITHUB_ENV
            echo "GPG_TTY=$(tty)" >> $GITHUB_ENV
            echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
      - name: Verify LLVM is being used
        run: |
            which clang
            clang --version
            llvm-config --version
      - name: no-san
        run: make clang-no-san
      - name: san
        run: make clang-san
